Added bunch of conenctors from camel-kafka conenctors repo
datastax/pulsar-3rdparty-connector pull request #10
Opened 2022-10-28 03:44 UTC by dlg99

This PR adds 164 connectors from https://github.com/apache/camel-kafka-connector

Also adds generator and project template used to add the connectors. 

Connector docs: https://camel.apache.org/camel-kafka-connector/3.18.x/reference/index.html

2022-10-28 10:39 UTC, eolivelli approved these changes

2022-10-28 11:54 UTC, nicoloboschi requested changes

2022-10-28 11:54 UTC, nicoloboschi commented on camel.sh
> +targetroot="/Users/andreyyegorov/src/pulsar-3rdparty-connector"
please remove or adapt

2022-10-28 16:24 UTC, dlg99 commented on camel.sh
> +targetroot="/Users/andreyyegorov/src/pulsar-3rdparty-connector"
removed this and camel-template

2022-10-31 16:03 UTC, nicoloboschi approved these changes

2022-10-31 17:19 UTC, merged